import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/hero-event.jpg";
export default function HeroSection() {
    return (_jsxs("section", { className: "relative flex min-h-[70vh] items-center overflow-hidden pt-16 sm:min-h-[80vh] lg:min-h-[88vh]", children: [_jsxs("div", { className: "absolute inset-0", children: [_jsx("img", { src: heroImage, alt: "Elegant event setup", width: 1920, height: 1080, className: "h-full w-full object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-slate-950/80 via-slate-900/70 to-slate-900/20" })] }), _jsx("div", { className: "relative z-10 mx-auto w-full max-w-7xl px-4 py-20 sm:px-6 sm:py-24 lg:px-8 lg:py-32", children: _jsxs(motion.div, { initial: { opacity: 0, y: 30 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.7 }, className: "max-w-2xl", children: [_jsx("div", { className: "mb-4 inline-flex items-center rounded-full border border-white/20 bg-white/10 px-3 py-1 text-sm font-medium text-white/90 backdrop-blur", children: "Premium event rentals • Fast delivery • Trusted setup" }), _jsxs("h1", { className: "mb-5 text-4xl font-semibold leading-[1.05] tracking-tight text-white sm:text-5xl lg:text-7xl", children: ["Make Every Event", _jsx("br", {}), _jsx("span", { className: "text-[#ffbf7f]", children: "Unforgettable." })] }), _jsx("p", { className: "mb-8 max-w-xl text-base leading-8 text-slate-200 sm:text-lg", children: "Premium rental equipment for weddings, galas, corporate events, and celebrations. Curated quality, delivered to your venue." }), _jsx(Link, { to: "/products", children: _jsxs(Button, { size: "lg", className: "gap-2 rounded-full bg-white px-6 text-base font-semibold text-slate-900 hover:bg-[#fff2de]", children: ["Browse Collection", _jsx(ArrowRight, { className: "h-4 w-4" })] }) })] }) })] }));
}
