import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Menu, X, ShieldCheck } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
export default function Navbar() {
    const [open, setOpen] = useState(false);
    const location = useLocation();
    return (_jsxs("nav", { className: "fixed top-0 left-0 right-0 z-50 glass", children: [_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-14 sm:h-16 flex items-center justify-between", children: [_jsxs(Link, { to: "/", className: "text-lg sm:text-xl font-bold tracking-tight text-foreground", children: ["Event", _jsx("span", { className: "text-brand", children: "Luxe" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-4 lg:gap-8", children: [_jsx(Link, { to: "/", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "Home" }), _jsx(Link, { to: "/products", className: "text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: "Products" }), _jsxs(Link, { to: "/admin", className: "flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors", children: [_jsx(ShieldCheck, { className: "w-4 h-4" }), "Admin"] })] }), _jsx("button", { onClick: () => setOpen(!open), className: "md:hidden p-2 text-foreground", "aria-label": "Toggle menu", children: open ? _jsx(X, { className: "w-5 h-5" }) : _jsx(Menu, { className: "w-5 h-5" }) })] }), _jsx(AnimatePresence, { children: open && (_jsx(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: "auto" }, exit: { opacity: 0, height: 0 }, className: "md:hidden glass border-t border-border/50", children: _jsxs("div", { className: "px-4 sm:px-6 py-4 flex flex-col gap-3", children: [_jsx(Link, { to: "/", onClick: () => setOpen(false), className: "text-sm font-medium text-foreground py-2", children: "Home" }), _jsx(Link, { to: "/products", onClick: () => setOpen(false), className: "text-sm font-medium text-foreground py-2", children: "Products" }), _jsxs(Link, { to: "/admin", onClick: () => setOpen(false), className: "text-sm font-medium text-foreground py-2 flex items-center gap-1.5", children: [_jsx(ShieldCheck, { className: "w-4 h-4" }), " Admin"] })] }) })) })] }));
}
