import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { Menu, X, ShieldCheck } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
export default function Navbar() {
    const [open, setOpen] = useState(false);
    const location = useLocation();
    const isActive = (path) => location.pathname === path ? "text-foreground" : "text-muted-foreground hover:text-foreground";

    return (_jsxs("nav", { className: "fixed left-0 right-0 top-0 z-50 border-b border-border/60 bg-white/70 backdrop-blur-xl", children: [_jsxs("div", { className: "mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 text-lg font-semibold tracking-tight text-foreground sm:text-xl", children: [_jsx("span", { className: "flex h-9 w-9 items-center justify-center rounded-full bg-brand/10 text-sm font-bold text-brand", children: "EL" }), _jsxs("span", { children: ["Event", _jsx("span", { className: "text-brand", children: "Luxe" })] })] }), _jsxs("div", { className: "hidden items-center gap-6 md:flex", children: [_jsx(Link, { to: "/", className: `text-sm font-medium transition ${isActive("/")}`, children: "Home" }), _jsx(Link, { to: "/products", className: `text-sm font-medium transition ${isActive("/products")}`, children: "Products" }), _jsxs(Link, { to: "/admin", className: `flex items-center gap-1.5 text-sm font-medium transition ${isActive("/admin")}`, children: [_jsx(ShieldCheck, { className: "h-4 w-4" }), "Admin"] })] }), _jsx("button", { onClick: () => setOpen(!open), className: "rounded-full border border-border bg-white/80 p-2 text-foreground shadow-sm md:hidden", "aria-label": "Toggle menu", children: open ? _jsx(X, { className: "h-5 w-5" }) : _jsx(Menu, { className: "h-5 w-5" }) })] }), _jsx(AnimatePresence, { children: open && (_jsx(motion.div, { initial: { opacity: 0, height: 0 }, animate: { opacity: 1, height: "auto" }, exit: { opacity: 0, height: 0 }, className: "border-t border-border/60 bg-white/90 md:hidden", children: _jsxs("div", { className: "flex flex-col gap-2 px-4 py-4 sm:px-6", children: [_jsx(Link, { to: "/", onClick: () => setOpen(false), className: "rounded-xl px-3 py-2 text-sm font-medium text-foreground", children: "Home" }), _jsx(Link, { to: "/products", onClick: () => setOpen(false), className: "rounded-xl px-3 py-2 text-sm font-medium text-foreground", children: "Products" }), _jsxs(Link, { to: "/admin", onClick: () => setOpen(false), className: "flex items-center gap-1.5 rounded-xl px-3 py-2 text-sm font-medium text-foreground", children: [_jsx(ShieldCheck, { className: "h-4 w-4" }), "Admin"] })] }) })) })] }));
}
