import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getProductImage } from "@/lib/productImages";
import { CheckCircle, XCircle, Mail } from "lucide-react";
export default function ProductDetailModal({ product, open, onClose }) {
    if (!product)
        return null;
    return (_jsx(Dialog, { open: open, onOpenChange: onClose, children: _jsxs(DialogContent, { className: "max-w-[95vw] sm:max-w-lg md:max-w-2xl p-0 overflow-hidden rounded-2xl sm:rounded-3xl max-h-[90vh] overflow-y-auto", children: [_jsx("div", { className: "aspect-[4/3] sm:aspect-video overflow-hidden bg-secondary", children: _jsx("img", { src: getProductImage(product.id, product.image), alt: product.name, className: "w-full h-full object-cover" }) }), _jsxs("div", { className: "p-4 sm:p-6 space-y-3 sm:space-y-4", children: [_jsx(DialogHeader, { children: _jsx(DialogTitle, { className: "text-xl sm:text-2xl font-bold", children: product.name }) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Badge, { variant: "outline", className: "text-[10px] sm:text-xs", children: product.category }), product.available ? (_jsxs("span", { className: "flex items-center gap-1 text-[10px] sm:text-xs text-success font-medium", children: [_jsx(CheckCircle, { className: "w-3 h-3 sm:w-3.5 sm:h-3.5" }), " Available"] })) : (_jsxs("span", { className: "flex items-center gap-1 text-[10px] sm:text-xs text-destructive font-medium", children: [_jsx(XCircle, { className: "w-3 h-3 sm:w-3.5 sm:h-3.5" }), " Unavailable"] }))] }), _jsx("p", { className: "text-xs sm:text-sm text-muted-foreground leading-relaxed", children: product.description }), _jsxs("div", { className: "flex items-baseline gap-1.5", children: [_jsxs("span", { className: "text-2xl sm:text-3xl font-bold text-foreground", children: ["$", product.price] }), _jsxs("span", { className: "text-xs sm:text-sm text-muted-foreground", children: ["/ ", product.priceUnit] })] }), _jsxs(Button, { size: "lg", className: "w-full rounded-xl sm:rounded-2xl gap-2 bg-foreground text-background hover:bg-foreground/90 text-sm sm:text-base", children: [_jsx(Mail, { className: "w-4 h-4" }), "Inquire to Rent"] })] })] }) }));
}
